### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by baristaner** [Ayditor/HPW_Rewrite#1]
I Got this error guys i cant open spell menu i cant do spells 

[ERROR] addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:1097: attempt to call method 'GetPlayerSpell' (a nil value)
  1. unknown - addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:1097

[ERROR] addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:1097: attempt to call method 'GetPlayerSpell' (a nil value)
  1. unknown - addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:1097

[ERROR] addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:1097: attempt to call method 'GetPlayerSpell' (a nil value)
  1. unknown - addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:1097

[ERROR] addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:242: attempt to call method 'GetPlayerSkin' (a nil value)
  1. unknown - addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua:242

**Comment by EgrOnWire** [comment]
Investigating on it, await for further updates

**Comment by baristaner** [comment]
So When is come new updates

**Comment by baristaner** [comment]
by the way i just oppened magic wand rewrite and i cant see other wants need another plugin?

**Comment by baristaner** [comment]
![image](https://cloud.githubusercontent.com/assets/26165265/23551686/9d76d490-0020-11e7-8882-875429861b8e.png)

**Comment by Sachha** [comment]
Same problem for me :/

**Comment by baristaner** [comment]
![image](https://cloud.githubusercontent.com/assets/26165265/23551797/1d8ebdf0-0021-11e7-87c8-4fd925824960.png)
     

and there is no spell in the book

**Comment by baristaner** [comment]
[ERROR] addons/hpw_rewrite-master/lua/hpwrewrite/spellmanager.lua:868: bad argument #1 to 'Format' (string expected, got nil)
  1. Format - [C]:-1
   2. PlayerGiveLearnableSpell - addons/hpw_rewrite-master/lua/hpwrewrite/spellmanager.lua:868
    3. GiveSpells - addons/hpw_rewrite-master/lua/entities/entity_hpwand_kingbook.lua:16
     4. unknown - addons/hpw_rewrite-master/lua/entities/entity_hpwand_bookbase.lua:82

**Comment by Sachha** [comment]
Here's the log after the 1st player connected : 

```
2. unknown - lua/includes/extensions/net.lua:32
1. func - addons/wand/lua/hpwrewrite/net/client.lua:67
[ERROR] addons/wand/lua/hpwrewrite/net/client.lua:67: attempt to call method 'GetSpellById' (a nil value)

[[MyDarkRP] DiaZzZy|2|STEAM_0:1:62589599] Lua Error:


2. unknown - lua/includes/extensions/net.lua:32
1. func - addons/wand/lua/hpwrewrite/net/client.lua:140
[ERROR] addons/wand/lua/hpwrewrite/net/client.lua:140: attempt to call method 'GetLearnedSpells' (a nil value)

[[MyDarkRP] DiaZzZy|2|STEAM_0:1:62589599] Lua Error:


5. unknown - addons/wand/lua/autorun/hpwandrewrite.lua:642
4. LoadFile - addons/wand/lua/autorun/hpwandrewrite.lua:597
3. include - [C]:-1
2. unknown - addons/wand/lua/hpwrewrite/spelltree.lua:575
1. BuildNodes - addons/wand/lua/hpwrewrite/spelltree.lua:41
[ERROR] addons/wand/lua/hpwrewrite/spelltree.lua:41: attempt to call method 'GetSpells' (a nil value)

[[MyDarkRP] DiaZzZy|2|STEAM_0:1:62589599] Lua Error:


5. unknown - addons/wand/lua/autorun/hpwandrewrite.lua:637
4. LoadFile - addons/wand/lua/autorun/hpwandrewrite.lua:597
3. include - [C]:-1
2. unknown - addons/wand/lua/hpwrewrite/spellmanager.lua:30
1. AddCategory - addons/wand/lua/hpwrewrite/spellmanager.lua:27
[ERROR] addons/wand/lua/hpwrewrite/spellmanager.lua:27: table index is nil
```

You need to read this from bottom to the top. I hope it can help you :)

**Comment by baristaner** [comment]
Are you can open spell tree ? i cant because

**Comment by Sachha** [comment]
I can't open anything :/

**Comment by baristaner** [comment]
Yeah me too

**Comment by EgrOnWire** [comment]
@Sachha DarkRP is not compatible. Pirated copies of gmod also not compatible.

**Comment by baristaner** [comment]
i used in sandbox  but didnt work

**Comment by baristaner** [comment]
![image](https://cloud.githubusercontent.com/assets/26165265/23552255/93d82648-0023-11e7-8377-ec102309fd4c.png)

i download it in steam and here but didnt work

**Comment by baristaner** [comment]
Please fix it fast i love this addon

**Comment by Sachha** [comment]
@EgrOnWire I don't use a pirated copies of gmod. Btw, even in sandbox, it's the same error ... 

Try it in solo and sandbox and you will see ^^'

**Comment by Ayditor** [comment]
hey, cant you unsubsribe, download legacy version from GitHub and say what it does?

**Comment by Ayditor** [comment]
oh you have it already

**Comment by Ayditor** [comment]
hotfix: change gmod language to English or Russian if you get errors, working on fix right now
