### ISSUE TITLE
Ive held down the self cast key and it refuses to work

### ISSUE THREAD

**Issue by Aldronea** [Ayditor/HPW_Rewrite#28]
ive even used it on other keys like Mouse 3 and it refuses to work.

help?

**Comment by Inquiryel** [comment]
Some of the spells can't be self casted. As for those that can, check this to see what your bind is. If you are on a server, ask what they have as the default bind. 
![backspace](https://user-images.githubusercontent.com/32186638/34456740-79fd08a4-ed64-11e7-967f-1e77494630ec.png)
or;
![20171230132715_1](https://user-images.githubusercontent.com/32186638/34456767-41cd24a4-ed65-11e7-8fd3-940085a97731.jpg)

I know there is a file to change the key but try this for now.
