### ISSUE TITLE
Wand Broken?

### ISSUE THREAD

**Issue by Darth-Seb** [Ayditor/HPW_Rewrite#34]
DPropertySheet:AddSheet tried to add invalid panel!
Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 161	"AddSheet"		lua/vgui/dpropertysheet.lua
	3: Line 1976	"OpenNewSpellManager"		addons/hpw_rewrite-master/lua/hpwrewrite/vgui.lua
	4: Line 1162	"nil"		addons/hpw_rewrite-master/lua/weapons/weapon_hpwr_stick.lua

https://www.youtube.com/watch?v=rLhTBYQaY4E

If the video is confusing basically my wand will swing but not actually use the spell. When I open the spell menu the first time I enter the game the error from the top will pop up. The only way I can use the spell is actually pressing the bind button and I prefer to click my mouse button instead.

**Comment by Darth-Seb** [comment]
I'd like to add ignore the YT video name that was meant for the Hogwarts RP server staff team because we are quite friendly with each other and I thought it was a serverside error.

**Comment by EgrOnWire** [comment]
@Ayditor https://github.com/Ayditor/HPW_Rewrite/blob/4bd8f9c7b70537fa86eacee9b2b96afa4bf713a0/lua/hpwrewrite/vgui.lua#L1723
May be caused by this line.

**Comment by Inquiryel** [comment]
@EgrOnWire hey so I helped this person with this, and we simply decided to just have them reinstall Gmodand all there addons. This has been solved.

**Comment by Darth-Seb** [comment]
Well, factory reset but yeah basically the same thing.
