### ISSUE TITLE
Issue with the Modification on Gmod !

### ISSUE THREAD

**Issue by chrischi16** [Ayditor/HPW_Rewrite#4]
2( error, your addons list, GMod language ) The wand is not working, it says Magic Wand is creating script errors I can't even right click to open menu or else i just can left click for a little " bzzt " I check the console and it's spamming some error message i can't copy it it's to fast , Addons: Magic Wand Rewrite, ULib , ULX , P2P Hero and Blood and Gore Overhaul IV , German
3( when this error happens ) when i first activated the Mod and equiped the wand

**Comment by Ayditor** [comment]
try changing gmod language to english

**Comment by Ayditor** [comment]
if that will work, try to download legacy version of the wand from GitHub and install it instead of workshop one or just reinstall workshop version

**Comment by chrischi16** [comment]
Changing the language ? What's the difference? it will be the same anyway just with english ui

**Comment by Ayditor** [comment]
just try it

**Comment by Ayditor** [comment]
I will be afk for some hours

**Comment by EgrOnWire** [comment]
I doubt that you have less than 8 addons. Citation needed

**Comment by chrischi16** [comment]
I just have those 4+1 Mods installed

**Comment by chrischi16** [comment]
Anyway, I'am looking for a Solution for this Problem. Not for an Argument.

**Comment by EgrOnWire** [comment]
what is the error doing
what is the console out
we cant go blind onto that one

**Comment by Sachha** [comment]
Did you try to change your gmod language to English at least?

**Comment by Sachha** [comment]
Ok, i've tested and yhea, it's the same problem since yesterday. 

Remplace everything in the "dictionnary.lua" with this : https://github.com/Sachha/HPW_Rewrite/blob/7e5931a0326cd14908be98388aea3f43f29016f4/lua/hpwrewrite/dictionary.lua

I've sended a pull requested but they denied it, I don't know why

**Comment by Ayditor** [comment]
updated
