### ISSUE TITLE
Gmod - Harry Potter Wand Mod Bug

### ISSUE THREAD

**Issue by FoxyPirateFox01** [Ayditor/HPW_Rewrite#7]
I was trying to shoot a spell through a portal, using the portal gun mod (https://steamcommunity.com/sharedfiles/filedetails/?id=336509414&searchtext=portal), but it wouldn't let me. It just bounced off like there was nothing there portal-like. Usually, this portal gun mod would let you walk through, well, portals, and you can shoot through them too. Thats why I even tried it in the first place. Please fix.

**Comment by EgrOnWire** [comment]
We're not planning on adding some thirdparty addon support we never cared of.
